# Generated by Django 2.1.1 on 2018-09-16 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_order', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(verbose_name='date published')),
                ('due_on', models.DateTimeField(verbose_name='date published')),
                ('owner', models.CharField(choices=[('ADM', 'Admin'), ('GST', 'Guest')], default='ADM', max_length=2)),
                ('mark', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_list_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='list_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Task_List'),
        ),
    ]
