# Generated by Django 2.1.1 on 2018-09-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='owner',
            field=models.CharField(choices=[('ADM', 'Admin'), ('GST', 'Guest')], default='ADM', max_length=5),
        ),
    ]
