# Generated by Django 2.1.3 on 2018-11-10 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_order', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(verbose_name='date published')),
                ('due_on', models.DateTimeField(verbose_name='date published')),
                ('owner', models.CharField(choices=[('ADM', 'Admin'), ('GST', 'Guest')], default='ADM', max_length=5)),
                ('mark', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_list_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(verbose_name='date published')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='list_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Task_List'),
        ),
    ]
